# Generated by Django 4.0.4 on 2022-05-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.IntegerField(default=1)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=225)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=225, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=225, null=True)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('if_lead', models.IntegerField(blank=True, null=True)),
                ('tsize', models.CharField(blank=True, max_length=5, null=True)),
                ('otc', models.IntegerField(blank=True, null=True)),
                ('oti', models.IntegerField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=225, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn', models.CharField(blank=True, max_length=11, null=True)),
                ('driving_licence', models.CharField(blank=True, max_length=20, null=True)),
                ('dl_expiry', models.DateField(blank=True, null=True)),
                ('state_of_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.IntegerField(blank=True, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=225, null=True)),
                ('resident_address', models.TextField(blank=True, null=True)),
                ('personal_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('reporting_office', models.CharField(blank=True, max_length=225, null=True)),
                ('emg_name', models.CharField(blank=True, max_length=225, null=True)),
                ('emg_number', models.CharField(blank=True, max_length=225, null=True)),
                ('emg_relation', models.IntegerField(blank=True, null=True)),
                ('emg2_name', models.CharField(blank=True, max_length=225, null=True)),
                ('emg2_number', models.CharField(blank=True, max_length=225, null=True)),
                ('emg2_relation', models.IntegerField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('linkedin', models.TextField(blank=True, null=True)),
                ('blog', models.TextField(blank=True, null=True)),
                ('user_pic', models.ImageField(blank=True, null=True, upload_to='user')),
                ('user_qr', models.ImageField(blank=True, null=True, upload_to='user_qr')),
                ('probation_till', models.DateField(blank=True, null=True)),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('login_token', models.CharField(blank=True, max_length=225, null=True)),
                ('secret_code', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(0, 'USA'), (1, 'INDIA')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inspect_docs',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.country')),
            ],
        ),
        migrations.CreateModel(
            name='Job_title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mail_settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(blank=True, max_length=90, null=True)),
                ('host', models.CharField(blank=True, max_length=90, null=True)),
                ('port', models.CharField(blank=True, max_length=90, null=True)),
                ('user', models.CharField(blank=True, max_length=90, null=True)),
                ('passw', models.CharField(blank=True, max_length=90, null=True)),
                ('from_data', models.CharField(blank=True, max_length=90, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=90, null=True)),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('page_role_column', models.CharField(blank=True, max_length=100, null=True)),
                ('orderby', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_mg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uan', models.CharField(blank=True, max_length=225, null=True)),
                ('esi', models.CharField(blank=True, max_length=100, null=True)),
                ('background', models.CharField(blank=True, max_length=100, null=True)),
                ('pension', models.IntegerField(blank=True, null=True)),
                ('appraisal', models.DateField(blank=True, null=True)),
                ('medical_card', models.TextField(blank=True, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=225, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspect_media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_name', models.CharField(blank=True, max_length=225, null=True)),
                ('date', models.DateField()),
                ('caption', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.inspect_docs')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City_zip_state',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('county_area', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=30, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=30, null=True)),
                ('some_field', models.IntegerField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, max_length=30, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.country')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='job_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.country'),
        ),
        migrations.AddField(
            model_name='users',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.job_title'),
        ),
        migrations.AddField(
            model_name='users',
            name='permanent_zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_perm_zip', to='authentication.city_zip_state'),
        ),
        migrations.AddField(
            model_name='users',
            name='resident_zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_resi_zip', to='authentication.city_zip_state'),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.roles'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
